# Starship config

# Inserts a blank line between shell prompts
# format = "$all$time$status$shell$character"
# right_format = "$time"
add_newline = true

# Replace the "â¯" symbol in the prompt with "âœ"
[character] # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green)" # The "success_symbol" segment is being set to "âœ" with the color "bold green"

[time]
disabled = true
format = 'at[ $time ğŸ•™]($style) '
time_format = "%T"
# utc_time_offset = "-5"
# time_range = "10:00:00-14:00:00"

[username]
show_always = true
